default_language_version:
  python: python3.9

repos:
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    name: black-bridge
    files: ^bridge
  - id: black
    name: black-flare
    files: ^flare

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    name: flake8-bridge
    files: ^bridge/bridge|^bridge/tests|^bridge/examples
  - id: flake8
    name: flake8-flare
    files: ^flare/flare|^flare/tests|^flare/examples

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    name: flake8-bridge
    files: ^bridge/bridge|^bridge/tests|^bridge/examples
  - id: mypy
    name: flake8-flare
    files: ^flare/flare|^flare/tests|^flare/examples
