default_language_version:
  python: python3.9

repos:
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    files: ^bridge/bridge|^bridge/tests

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    files: ^bridge/bridge|^bridge/tests

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    files: ^bridge/bridge|^bridge/tests
